### ISSUE TITLE
[BUG] dimensions="height < 400&& width < 2000 && width > 2 * height" 

### ISSUE THREAD

**Issue by kimcrab** [deiwin/ngImageInputWithPreview#3] opened 2015-07-30 03:25 UTC
First of all, This is what I'm looking for! Thanks a lot!

When I set the dimensions like this -->  `dimensions="height < 400&& width < 2000 && width > 2 * height"`
Even if I upload very small size picture, It shows the error "Invalid dimensions! Expecting a landscape image smaller than 1800x400." 
So, I changed dimensions like this -->  `dimensions="height < 400"`
And it works perfectly (bleow 400 height works nice, over 400 hight shows error)
What do you think is the problem? 

And I think you have to show how to inject this MODULE for beginers.

**Comment by deiwin** [comment] 2015-07-30 16:18
That seems weird. I'll have a look this weekend.

Thanks for reporting!

**Comment by deiwin** [comment] 2015-08-01 15:21
Could not reproduce. I added a test for it  at 4d4c3af, but notice that I changed `2 * height` to be `0.5 * height` because I run the test with a 1x1 image and otherwise it would've failed.

Can you please check and report the dimensions of the images you used? I'll close this for now.

**Closed as completed by deiwin** 2015-08-01 15:21 UTC
Labels: bug, invalid

**Comment by kimcrab** [comment] 2015-08-03 01:16
@deiwin  Thanks it's solved!!
